
Create Column Table IK_DISP_PARAMETERS
(
Num Integer not null primary key generated by default as IDENTITY,
DspDocE nVarchar(10),
DspDocN nVarchar(15),
DspDocL nVarchar(10),
DelDocE nVarchar(10),
DelDocN nVarchar(15),
DelDocL nVarchar(10),
SamNo Integer,
ItemC nVarchar(50),
QCClear nVarchar(5),
ParaC nVarchar(50),
ParaN nVarchar(100),
ParamTyp nVarchar(50),
UoM nVarchar(15),
SReadngV nVarchar(3),
SReadng Decimal(19,2),
TolPlus Decimal(19,2),
TolMinus Decimal(19,2),
Instrmnt nVarchar(50),
ActRead Decimal(19,2),
ActReadV nVarchar(3),
Remarks nVarchar(100),
MacID nVarchar(100)
)