
/*
Created By			: Vijeesh P.S
Created Date		: 20/07/2017
Tables Used			: 
Notes				: Parameter Selection
Execution Sample	: Call IK_INWARD_INSPECTION_PARAMETERS ('5','10701-004000000023-000','5','1','5','','0','1_P001_SDC-MUM_SDCT_5_0_10701-004000000023-000')
Drop Procedure		: Drop Procedure IK_INWARD_INSPECTION_PARAMETERS
Update Reason		: 
Updated By			: 
Update Date			: 
*/

CREATE PROCEDURE IK_INWARD_INSPECTION_PARAMETERS
(IN NoOfSamples nVarchar(10),
IN ItemCode nVarchar(50),
IN InwardNo nVarchar(15),
IN InwardLine nVarchar(10),
IN GRPODocE nVarchar(10),
IN GRPODocN nVarchar(15),
IN GRPODocL nVarchar(10),
IN MacID nVarchar(5000)
)
LANGUAGE SQLSCRIPT SQL SECURITY INVOKER 
As
Begin

Declare vLoop1 Integer = 1;

Create Column Table IK_TMP_PARAMETERS
(
"NUM" Integer not null Primary key generated by default as identity,
"INWDOCE" nVarchar(10),
"INWDOCN" nVarchar(15),
"INWDOCL" nVarchar(10),
"GRPODOCE" nVarchar(10),
"GRPODOCN" nVarchar(15),
"GRPODOCL" nVarchar(10),
"SAMNO" Integer,
"ITEMC" nVarchar(50),
"QCCLEAR" nVarchar(5),
"PARAC" nVarchar(50),
"PARAN" nVarchar(100),
"UOM" nVarchar(15),
"SREADNG" Decimal(19,2),
"TOLPLUS" Decimal(19,2),
"TOLMINUS" Decimal(19,2),
"INSTRMNT" nVarchar(50),
"ACTREAD" Decimal(19,2),
"REMARKS" nVarchar(100),
"MACID" nVarchar(100)
);

While :vLoop1 <= :NoOfSamples Do

	Insert Into IK_TMP_PARAMETERS
	(
	"INWDOCE",
	"INWDOCN",
	"INWDOCL",
	"GRPODOCE",
	"GRPODOCN",
	"GRPODOCL",
	"SAMNO",
	"ITEMC",
	"QCCLEAR",
	"PARAC",
	"PARAN",
	"UOM",
	"SREADNG",
	"TOLPLUS",
	"TOLMINUS",
	"INSTRMNT",
	"ACTREAD",
	"REMARKS",
	"MACID"
	)
	Select '         ' "INWDOCE"
	,:InwardNo "INWDOCN"
	,:InwardLine "INWDOCL"
	,:GRPODocE "GRPODOCE"
	,:GRPODocN "GRPODOCN" 
	,:GRPODocL "GRPODOCL"
	,:vLoop1 "SAMNO"
	,:ItemCode "ITEMC"
	,'' "QCCLEAR"
	,T1."U_ParaC" "PARAC"
	,T1."U_ParaN" "PARAN"
	,T1."U_UoM" "UOM"
	,T1."U_SReadng" "SREADNG" 
	,T1."U_TolPlus" "TOLPLUS"  
	,T1."U_TolMinus" "TOLMINUS"
	,T1."U_Instrmnt" "INSTRMNT"
	,0.00 "ACTREAD"
	,'                                                                                                ' "REMARKS"
	,:MacID "MACID"  
	From "@IK_QLTP" T0 Inner Join "@IK_LTP1" T1 On T0."Code" = T1."Code"
	Where T0."U_MacCode" = :ItemCode And IfNull(T1."U_IsADspt",'N') = 'N';
	
vLoop1 := vLoop1 + 1;

End While;

Select "INWDOCE","INWDOCN" "InwardInspection No","INWDOCL","GRPODOCE","GRPODOCN","GRPODOCL","SAMNO" "Sample Size","ITEMC" "Item Code","PARAC" "Parameter Code"
,"PARAN" "Parameter Name","UOM","SREADNG" "Std.Reading","TOLPLUS" "Tolerance (+)","TOLMINUS" "Tolerance (-)","QCCLEAR" "QC Clearance","INSTRMNT" "Instrument"
,"ACTREAD" "Actual Reading","REMARKS" "Remarks","MACID" "MacID"
From IK_TMP_PARAMETERS;

Drop Table IK_TMP_PARAMETERS;

End
